language: rust
cache: cargo

before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup install nightly
- cargo +nightly install --force rustfmt-nightly
- cargo +nightly fmt -- --write-mode diff

script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test