language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
before_script:
- rustup component add rustfmt
script:
- cargo build
- cargo test
- cargo fmt --all -- --check

before_deploy:
- cargo doc
- cargo package
deploy:
  provider: releases
  on:
    tags: true
    repo: AayushiShukla2606/travis-script
    branch: master
after_deploy:
- cargo publish --token "$CRATES_IO_TOKEN"
