[package]
name = "travis-script"
version = "0.1.0"
authors = ["AS <aayushishuklartm@gmail.com>"]
description = "A short description of my package"

[dev-dependencies]
pulldown-cmark = "0.2.0"
reqwest = "0.9.5"
